{!!HTML::style('themes/itim_world/assets/css/plugins/froala/froala_editor.css')!!}
{!!HTML::style('themes/itim_world/assets/css/plugins/froala/plugins/char_counter.min.css')!!}
{!!HTML::style('themes/itim_world/assets/css/plugins/froala/plugins/code_view.min.css')!!}
{!!HTML::style('themes/itim_world/assets/css/plugins/froala/plugins/colors.min.css')!!}
{!!HTML::style('themes/itim_world/assets/css/plugins/froala/plugins/emoticons.min.css')!!}
{!!HTML::style('themes/itim_world/assets/css/plugins/froala/plugins/file.min.css')!!}
{!!HTML::style('themes/itim_world/assets/css/plugins/froala/plugins/fullscreen.min.css')!!}
{!!HTML::style('themes/itim_world/assets/css/plugins/froala/plugins/image.min.css')!!}
{!!HTML::style('themes/itim_world/assets/css/plugins/froala/plugins/image_manager.min.css')!!}
{!!HTML::style('themes/itim_world/assets/css/plugins/froala/plugins/line_breaker.min.css')!!}
{!!HTML::style('themes/itim_world/assets/css/plugins/froala/plugins/quick_insert.min.css')!!}
{!!HTML::style('themes/itim_world/assets/css/plugins/froala/plugins/table.min.css')!!}
{!!HTML::style('themes/itim_world/assets/css/plugins/froala/plugins/video.min.css')!!}
